### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by wavexx** [TabViewer/gtabview#24]
Would definitely be nice to have as I used anaconda3 on windows in several occasions, but don't have enough time to commit to this.

Any help would be appreciated.

**Comment by scls19fr** [comment]
Hi Yuri,

I have no experience with conda packaging but someone send a PR
for one of my lib
You might have a look
https://github.com/ioos/conda-recipes/pull/420/files

Kind regards

**Comment by goanpeca** [comment]
@wavexx I can help making a conda-package for this ;-)

**Comment by wavexx** [comment]
Anything I can do to help this?

**Comment by goanpeca** [comment]
@wavexx I created a quick recipe on conda-forge

https://github.com/conda-forge/staged-recipes/pull/2934

**Comment by wavexx** [comment]
Got to this with some non-chalant delay ;).
I temporarily moved the gtabview tool into it's own dedicated module until a proper fix for #33 is done.

This should allow us to get a proper conda package. @goanpeca can we revisit this?

**Comment by wavexx** [comment]
I've released and uploaded 0.9 to pypi with this change

**Comment by wavexx** [comment]
My first attempt: https://github.com/conda-forge/staged-recipes/pull/13563

**Comment by wavexx** [comment]
@scls19fr could you review the above? At least on windows it seems that the "gtabview" is not recognized as a command after installation, which seems rather surprising.

**Comment by wavexx** [comment]
Package went in!

https://anaconda.org/conda-forge/gtabview
