### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by shadiakiki1986** [TabViewer/gtabview#31]
Neat tool. Just tried it out. Needed the following steps to get the following to work

```
sudo apt-get install python3-pyqt5
pip install PyQt5 gtabview # <<<< PyQt5 not included in readme
export QT_API=pyqt5 # <<<< this env var was not included in readme
```

example.py script
```
from gtabview import view

# numpy arrays up to two dimensions are supported
import numpy as np
view(np.array([[1, 2, 3], [4, 5, 6]]))
```

and now `python3 example.py` works.

Is this expected or am I missing something?
I don't see it in the README.

**Comment by wavexx** [comment]
On Thu, Sep 26 2019, Shadi Akiki wrote:
> sudo apt-get install python3-pyqt5

With this you install pyqt5 for the entire system.

> pip install PyQt5 gtabview

This installs pyqt5 for the current env/user. One of those is redundant,
depending on what you're trying to do.

> export QT_API=pyqt5

This *might* be needed if your system has both pyqt4 and pyqt5, but
shouldn't be necessary either.

Note that gtabview uses pyqt4/5/pyside automatically if already loaded.
When nothing has been loaded yet, the default is already pyqt5.

**Comment by wavexx** [comment]
Closing this
