### ISSUE TITLE
viewer broken for arrays with more than 65 rows

### ISSUE THREAD

**Issue by neili02** [TabViewer/gtabview#35]
gtabview = 10.0
python = 3.7.8.final.0

To replicate problem:

```
import gtabview
gtabview.view( numpy.zeros((66,10))

```
Produces the following error, apparently related to line 370 of viewer code:

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-6-4341f160e3dc> in <module>
----> 1 gtabview.view( numpy.zeros((66,10)))

~\anaconda3\envs\image\lib\site-packages\gtabview\__init__.py in view(data, enc, start_pos, delimiter, hdr_rows, idx_cols, sheet_index, transpose, wait, recycle, detach, metavar, title, sort)
    151     view_kwargs = {'hdr_rows': hdr_rows, 'idx_cols': idx_cols,
    152                    'start_pos': start_pos, 'metavar': metavar, 'title': title}
--> 153     VIEW.view(model, view_kwargs, wait=wait, recycle=recycle)
    154     return VIEW

~\anaconda3\envs\image\lib\site-packages\gtabview\__init__.py in view(self, data, view_kwargs, wait, recycle)
     46         if self._view is None or not recycle:
     47             self._view = Viewer()
---> 48         self._view.view(data, **view_kwargs)
     49         if wait:
     50             self.wait()

~\anaconda3\envs\image\lib\site-packages\gtabview\viewer.py in view(self, model, hdr_rows, idx_cols, start_pos, metavar, title, relayout)
    471 
    472         if relayout or old_model is None:
--> 473             self.table.resizeColumnsToContents()
    474 
    475         self.table.setFocus()

~\anaconda3\envs\image\lib\site-packages\gtabview\viewer.py in resizeColumnsToContents(self)
    438     def resizeColumnsToContents(self):
    439         self._autosized_cols = set()
--> 440         self._resizeColumnsToContents(self.table_level, self.table_index, self._max_autosize_ms)
    441         self._update_layout()
    442 

~\anaconda3\envs\image\lib\site-packages\gtabview\viewer.py in _resizeColumnsToContents(self, header, data, limit_ms)
    399             max_col_ms = limit_ms / max(1, max_col)
    400         for col in range(max_col):
--> 401             self._resizeColumnToContents(header, data, col, max_col_ms)
    402 
    403     def eventFilter(self, obj, event):

~\anaconda3\envs\image\lib\site-packages\gtabview\viewer.py in _resizeColumnToContents(self, header, data, col, limit_ms)
    383     def _resizeColumnToContents(self, header, data, col, limit_ms):
    384         hdr_width = self._sizeHintForColumn(header, col, limit_ms)
--> 385         data_width = self._sizeHintForColumn(data, col, limit_ms)
    386         if data_width > hdr_width:
    387             width = min(self.max_width, data_width)

~\anaconda3\envs\image\lib\site-packages\gtabview\viewer.py in _sizeHintForColumn(self, table, col, limit_ms)
    378                 if lm_elapsed >= limit_ms:
    379                     break
--> 380                 lm_row = int((row / lm_elapsed) * limit_ms)
    381         return max_width
    382 

ZeroDivisionError: float division by zero

**Comment by wavexx** [comment]
Ok, that's seems pretty clear that autosizing is so quick (or, more likely, the resolution of clock() being low-enough) to result in lm_elapsed to be zero. Should be easy to fix, I'll have a look.

**Comment by wavexx** [comment]
@neili02 can you check if the current master works as intended?

**Comment by neili02** [comment]
The update has fixed the problem. Thanks for the speedy correction. My quick interim fix had been to set lm_row to max_row.
